### ISSUE TITLE
[BUG] error when default prop in track is omitted on Android

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#10]
**Describe the bug**
I got a "Error while updating property 'config' of a view managed by : RNJWPlayerView" error box when running on Android that I was able to slowly narrow down to omitting a `default` property on a track in the config, e.g.:
```js
          tracks: [
            {
              file: `${jwPlayerBase}strips/${id}-120.vtt`,
              label: 'thumbnails',
              // no 'default' prop
            },
          ],
```

It appears to be coming from on or around [this line](https://github.com/jwplayer/jwplayer-react-native/blob/5b68985aea8392777bb257fab70e1cecd731d3a7/android/src/main/java/com/jwplayer/rnjwplayer/Util.java#L150), despite `default` being [marked optional ](https://github.com/jwplayer/jwplayer-react-native/blob/5b68985aea8392777bb257fab70e1cecd731d3a7/index.d.ts#L257) in TypeScript. Maybe `trackProp.hasKey("default") ? trackProp.getBoolean("default") : false` would solve this.

**To Reproduce**
Try to set a config with a track but with no `default` property, then run the app on Android.

**Expected behavior**
Default defaults to false if not supplied, no error.

**Screenshots / Visual evidence**
<img width="372" alt="Screenshot 2024-05-04 at 11 23 07 PM" src="https://github.com/jwplayer/jwplayer-react-native/assets/1103467/78723da3-47af-402e-a477-46a51988fc16">

**Additional Information**
I actually encountered this on chaimPaneth's version, but I see the same code here, so I'm cross-filing it.

**Comment by chriszs** [comment]
(There's a [similar structure](https://github.com/jwplayer/jwplayer-react-native/blob/5b68985aea8392777bb257fab70e1cecd731d3a7/android/src/main/java/com/jwplayer/rnjwplayer/Util.java#L101) around `sources.file.default`, I wonder if it has the same problem.)

**Comment by chriszs** [comment]
Semi-related, but the next line appears to set the track kind to captions, which prevents a thumbnail track from being used.

**Comment by Jmilham21** [comment]
This has been resolved, and so has the issue related to only captions being parsed in `tracks`. A release with these changes should be coming to NPM sometime this week.
