### ISSUE TITLE
Delay for iOS videos

### ISSUE THREAD

**Issue by dev-1235813** [jwplayer/jwplayer-react-native#102]
![ad50fb1e-ef9c-4147-b2cc-3f6e11cd7c22](https://github.com/user-attachments/assets/10df2535-bc31-43b3-8050-53508f755e99)

For longer videos on iOS I have problem with long time black screen after preroll. Sometimes around 20-30s. Android implementation works fine in that case. 

My ad config 
`    advertising: {
                adClient: 'ima',
                adSchedule: [
                    {
                        offset: 'pre',
                        tag: vastTag,
                    },
                ],
            },`

**Comment by Jmilham21** [comment]
@dev-1235813 this should be resolved in the `1.0.3` release.

We found the issue was related to how non-HLS content was being loaded in the native SDK. A patch was applied to iOS [4.21.1](https://releases.jwplayer.com/ios-4.21.1-3e03Pq) that allowed for the fix in this library.
