### ISSUE TITLE
[BUG] iOS jwplayer example - ListExample seekTo not working

### ISSUE THREAD

**Issue by leinnus** [jwplayer/jwplayer-react-native#106]
**Describe the bug**
iOS ListExample seekTo() not working

Example/app/jsx/screens/ListExample.js

```javascript

  const onBeforePlay = tag => {
    tags.map(player => {
      if (player !== tag) {
        playerRef.current[player]?.pause();
      }
    });

    playerRef.current['JWPlayer-1']?.seekTo('11');
  };

```

package.json
```javascript
  "dependencies": {
    "@jwplayer/jwplayer-react-native": "https://github.com/jwplayer/jwplayer-react-native.git",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/native-stack": "^7.1.14",
    "react": "18.3.1",
    "react-native": "0.76.4",
    "react-native-bootsplash": "^6.3.2",
    "react-native-device-info": "^14.0.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.21.2",
    "react-native-orientation-locker": "^1.7.0",
    "react-native-safe-area-context": "^5.0.0",
    "react-native-screens": "^4.3.0",
    "react-native-vector-icons": "^10.2.0",
    "rn-iphone-helper": "^2.0.4"
  },

```

**To Reproduce**
Nothing note worthy here to reproduce

***Steps to reproduce the behavior:***
1. touch play icon
2. skip to 11 sec

**Expected behavior**
seek to 11 sec

**Screenshots / Visual evidence**
![image](https://github.com/user-attachments/assets/22f39e51-af7b-42e5-8be8-46c1b3bd3dd2)

 
**Device(s) affected**
 - Device: iPhone14
 - OS: iOS 18.1
 -

**Comment by leinnus** [comment]
Not working.
```
playerRef.current['JWPlayer-1']?.seekTo(11);
```
also not working.
```
playerRef.current['JWPlayer-1']?.play();
```

**Comment by Jmilham21** [comment]
@leinnus, you're correct; the issue is most likely related to your react-native version. Our library must still be prepared for production in the new architecture (bridgeless) model. I'd suggest that for now, if possible, to [opt out](https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here#opt-out).

I'll review what it will take for us to become usable in the new framework.
