### ISSUE TITLE
[FEAT] make badge-maker a dev dependency

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#37]
**Is your feature request related to a problem? Please describe.**
Checking the diff when switching to this version I notice it includes dependencies badge-maker and its dependencies and sub-dependencies: anafanafo, binary-search, char-width-table-consumer, css-color-converter, css-unit-converter. These aren't required for the library to function, but seem to be used in development to produce the badges displayed on GitHub. It'd be nice not to have to include them.

**Describe the solution you'd like**
Putting badge-maker in devDependenices might solve it?

**Comment by Jmilham21** [comment]
Approved and merged. Thanks @chriszs
