### ISSUE TITLE
[FEAT] replace lodash dep for improved bundle size

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#41]
**Is your feature request related to a problem? Please describe.**
I'm trying out Expo's new [Atlas bundle visualizer](https://expo.dev/blog/introducing-expo-atlas), and I notice that lodash is one of the largest dependencies in the app's bundle: it's about 559 kb or about 3.45% of the overall bundle size.

<img width="1082" alt="Screenshot 2024-06-04 at 4 36 23 PM" src="https://github.com/jwplayer/jwplayer-react-native/assets/1103467/c3b2c2e9-200f-40c3-b499-e9666139cbbb">

It's required as a development dependency by jwplayer-react-native, but it looks like it's included in index.js, where it's used for [one comparison](https://github.com/jwplayer/jwplayer-react-native/blob/415d52ca8ab31d673e131cb406c3bae840b47840/index.js#L392).

**Describe the solution you'd like**
I propose changing this dependency to [lodash.isequalwith](https://www.npmjs.com/package/lodash.isequalwith), which should be way smaller and perform identically.

**Additional context**
Installing lodash components separately is what every other library I've installed seems to do, probably for the same reason. This should probably be a non-dev dep.

**Comment by Jmilham21** [comment]
This is a valid change and does shrink the bundle (never bad).

**Comment by Jmilham21** [comment]
Approved your PR. Good catch.
