### ISSUE TITLE
[BUG] setVolume method does not work on iOS

### ISSUE THREAD

**Issue by rcymborski-obe** [jwplayer/jwplayer-react-native#43]
**Describe the bug**
The `setVolume` method does not work on iOS. Regardless of how I set the volume using the `setVolume` method, the volume remains unchanged.

**To Reproduce**
Use the `Example` application as reference material and a starting place to reproduce any bugs.

***Steps to reproduce the behavior:***
1. Set up the JWPlayer configuration as shown in the example.
2. Create a reference to the JWPlayer instance.
3. Implement a function to set the volume using setVolume method.
4. Trigger the function after the player is ready (in this example, after 5 seconds).

Example code to reproduce:
```javascript
import JWPlayer, {Config} from '@jwplayer/jwplayer-react-native';
import React, {useRef} from 'react';
import {
  SafeAreaView,
  StatusBar,
  StyleSheet,
  useColorScheme,
  View,
} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';

const jwPlayerConfig: Config = {
  enableLockScreenControls: true,
  license: 'myLicense',
  pipEnabled: false,
  backgroundAudioEnabled: true,
  autostart: true,
  playlist: [
    {
      description: 'Test',
      file: 'filePath',
      image: 'fileThumb',
      title: 'barre cardio 45',
    },
  ],
};

function App(): React.JSX.Element {
  const jwPlayerRef = useRef<JWPlayer>(null);
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  const onPlayerReady = () => {
    // silence audio after 5 seconds
    setTimeout(() => {
      console.log('Should silence video audio');
      jwPlayerRef.current?.setVolume(0);
    }, 5000);
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <View style={styles.container}>
        <JWPlayer
          ref={jwPlayerRef}
          style={styles.player}
          onPlay={onPlayerReady}
          config={jwPlayerConfig}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    width: 380,
    height: 280,
  },
  player: {
    width: 380,
    height: 280,
  },
});

export default App;
```

**Expected behavior**
I expected the volume to be set to 0 (silenced) after 5 seconds when the setVolume method is called.

**Desktop (please complete the following information):**
npmPackages:
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Device(s) affected**
 - iPhone 15
 - iOS 17.0

**Comment by Jmilham21** [comment]
Hey @rcymborski-obe, I see you're putting a callback named `onPlayerReady` on the `onPlay` instead of the same named event. With the timeout you have, this shouldn't necessarily cause any issue, but calling `setVolume` before the player is ready _could_ cause the command to be ignored. 

I ran the Example app with a modified `SingleExample.js` like the below, and the `setVolume` command was respected and the volume was essentially muted after 5 seconds from `onPlayerReady`.

```js
import React, {useRef} from 'react';
import {StatusBar} from 'react-native';
import Player from '../components/Player';
import PlayerContainer from '../components/PlayerContainer';

export default () => {
  const playerRef = useRef([]);

  const onTime = e => {
    // var {position, duration} = e.nativeEvent;
    // eslint-disable-line
    // console.log('onTime was called with: ', position, duration);
  };

  const onPlayerReady = () => {
    setTimeout(() => {
      console.log('Should silence video audio');
      playerRef.current?.setVolume(0);
    }, 5000);
  };

  const onFullScreen = () => {
    StatusBar.setHidden(true);
  };

  const onFullScreenExit = () => {
    StatusBar.setHidden(false);
  };

  let jwConfig = {
    "title": "Single Inline Linear Preroll",
    "playlist": [
      {
        "title": "Single Inline Linear Preroll",
        "file": "https://content.bitsontherun.com/videos/q1fx20VZ-52qL9xLP.mp4",
        // "adschedule": {
        //   "adBreak1": {
        //     "offset": "pre",
        //     "ad": {
        //       "source": "googima",
        //       "tag": "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator="
        //     }
        //   }
        // }
      }
    ],
    "advertising": {
      "client": "googima"
    }
  }

  const renderPlayer = () => {
    return (
      <Player
        ref={playerRef}
        style={{flex: 1}}
        config={{
          autostart: true,
          styling: {
            colors: {},
          },
          ...jwConfig
        }}
        onTime={onTime}
        onPlay={onPlayerReady}
        onFullScreen={onFullScreen}
        onFullScreenExit={onFullScreenExit}
      />
    );
  };

  return (
    <PlayerContainer
      children={renderPlayer()}
      text="Welcome to jwplayer-react-native"
    />
  );
};

```

Please try running the Example or your own app with the changes I've shown. Let us know if you still experience the issue.

**Comment by chriszs** [comment]
I've been having the same issue and the supplied example didn't fix it in my testing. Specifically I tried this:
```js
      onPlayerReady={() => {
        console.log('Player ready', mute);
        if (mute) {
          setTimeout(() => {
            console.log('Muting', player.current?.setVolume);
            player.current?.setVolume(0);
          }, 5000);
        }
      }}
```

And I got "Muting [Function setVolume]" but the volume didn't mute.

Starting muted is my use case, so I also tried it with no `setTimeout` and that didn't seem to work either. Previously I tried wiring up a button with `setVolume(0)` and just hitting it repeatedly and that also didn't work.

**Comment by chriszs** [comment]
Set some break points in Xcode. Seems like the value setVolume is getting here is somehow `1`:

<img width="895" alt="Screenshot 2024-06-08 at 4 26 44 PM" src="https://github.com/jwplayer/jwplayer-react-native/assets/1103467/b2505a51-b7d6-46cb-ba00-b91538eb9bb0">

**Comment by chriszs** [comment]
When I change the `volume` `setVolume` accepts to an `NSNumber` and then do an explicit conversion to `doubleValue` I get the correct result:
```diff
-    @objc func setVolume(_ reactTag: NSNumber, _ volume: Double) {
+    @objc func setVolume(_ reactTag: NSNumber, _ volume: NSNumber) {
        self.bridge.uiManager.addUIBlock { uiManager, viewRegistry in
            guard let view = viewRegistry?[reactTag] as? RNJWPlayerView else {
                print("Invalid view returned from registry, expecting RNJWPlayerView, got: \(String(describing: viewRegistry?[reactTag]))")
                return
            }

            if let playerView = view.playerView {
-                playerView.player.volume = volume
+                playerView.player.volume = volume.doubleValue
            } else if let playerViewController = view.playerViewController {
-                playerViewController.player.volume = volume
+                playerViewController.player.volume = volume.doubleValue
            }
        }
    }
```

**Comment by chriszs** [comment]
Here are the relevant parts of `npx react-native info`:
```
SDKs:
  iOS SDK:
    Platforms:
      - iOS 17.2
IDEs:
  Xcode:
    version: 15.1/15C65
npmPackages:
  react: 18.2.0
  react-native: 0.74.1
  expo: ~51.0.9
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

**Comment by Jmilham21** [comment]
Thanks for looking into this @chriszs. I asked our iOS devs to take a look at your PR. It makes sense, even though I wasn't experiencing it in my build. Possibly, something about your React environment is changing the type in the bridge, and we lose the value. Either way, if the fix works I'm happy. Awaiting another review before approval.

**Comment by rcymborski-obe** [comment]
@chriszs solution fixed the issue on my end. Thank you!
