### ISSUE TITLE
[BUG] crash on iOS with new arch

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#48]
**Describe the bug**
App crashes with `Attempted to dereference null pointer.` when new arch/bridgeless is enabled and JWPlayer is viewed.

The crash appears to be in a string length check called indirectly by `parseExportedMethods` with a method selector of `setUpCastController`, a method signature of `nil` and a return type of `v` (void?), when attempting to call the signature. See below for screenshot.

If I had to guess, this may be because the cast methods are conditionally defined by `#if USE_GOOGLE_CAST` but the exported React Native method signatures may not be.

**To Reproduce**
***Steps to reproduce the behavior:***
1. Setup an app with JWPlayer, but don't enable Google Cast support
2. Enable new arch
3. Try to view a screen with JWPlayer on it

**Expected behavior**
No crash.

**Screenshots / Visual evidence**
<img width="1214" alt="Screenshot 2024-06-12 at 2 11 54 AM" src="https://github.com/jwplayer/jwplayer-react-native/assets/1103467/d449fceb-05a0-49d3-859d-3caa39e6688c">

Error occurs during a call on line 126 in the screenshot above.

**Comment by Jmilham21** [comment]
Hey @chriszs, I'll be on PTO from today until the end of the month. The rest of my team is aware of this and will look into it. I'm just giving you a heads-up if you don't see any motion for a bit. 

This may become a larger issue as supporting the architecture will require some major refactoring of our classes (or at least that was my understanding the last time I read through the docs).

**Comment by chriszs** [comment]
@Jmilham21 That may no longer be the case with bridgeless, which in some cases requires almost no changes at all, and those docs have evolved a _ton_, but I haven't yet confirmed that for JWPlayer. For me, this is not a priority, because in order to enable new arch multiple third party libraries would have to fix issues. But new arch will be the default in the next major release of React Native, and I suspect this crash could be relatively straightforward to address (though there can always be unforeseen complications).
