### ISSUE TITLE
[FEAT] Apple TV Support

### ISSUE THREAD

**Issue by anyarik** [jwplayer/jwplayer-react-native#5]
Do you guys have any plans to make jwplayer-react-native compatible with Apple TV in the future? it would be a great feature to have.

**Comment by Jmilham21** [comment]
Hey @anyarik, the JWP position is we will not be supporting Apple TV. 

If you need this and want to keep your player in the same package, it may be ideal to fork this repository and add separate logic for TV. Understandably, this would be a large undertaking, so I apologize for not being able to give more direct support. 

If you do take the path of adding in a TV package (even if through the native AVPlayer) and want to merge into the main branch, we'd be happy to review a PR.

I am closing for now as we will not accept this feature request.
