### ISSUE TITLE
[BUG] Enabling ads for iOS isn't compatible with ARM hardware

### ISSUE THREAD

**Issue by dominictobias** [jwplayer/jwplayer-react-native#50]
**Describe the bug**
This project uses an old version of GoogleAds-IMA-iOS-SDK which doesn't support ARM hardware, so it's not runnable on modern Mac Simulators for example:

https://github.com/jwplayer/jwplayer-react-native/blob/8493364b5b46d5962faf3143536ea89c0a4ff094/RNJWPlayer.podspec#L38

You can read about it here: https://groups.google.com/g/ima-sdk/c/y-5OHtAQ5rk?pli=1
https://github.com/googleads/googleads-ima-ios/issues/55
https://groups.google.com/g/ima-sdk/c/aGHtC7lSGgk

Should use at least v3.5 from what I read in last link ^

**To Reproduce**

Add `$RNJWPlayerUseGoogleIMA = true` to Podfile. Try to build on a Mac M1.

P.S. your instructions here are incorrect: https://github.com/jwplayer/jwplayer-react-native?tab=readme-ov-file#ios-advertising (Podfile doesn't have `ext{}`)

**Comment by dominictobias** [comment]
Nvm I see it says 3.22.0. So I don't know why it still fails

**Comment by dominictobias** [comment]
Re-opening as I found the cause and raising a PR. It is indeed a version issue

**Comment by Jmilham21** [comment]
@dominictobias I'm assigning this to a team member more familiar with our iOS SDK and with the right environment to test this. 

@david-almaguer Please take a look, as I don't have an M1 machine to confirm. I'd be surprised since our SDK targets `3.22.0,` and we didn't run into this in testing.

**Comment by dominictobias** [comment]
Thanks, this was specifically fixed in 3.22.1 and the version was pinned to
3.22.0

**Comment by Jmilham21** [comment]
I understand. We built the version of our SDK being used by React Native to work with and be tested on `3.22.0`. That's my concern; this would have come up in the native SDK testing, and if it didn't something else may be wrong here. 

We have started enforcing specific versions in React Native to match the version we test within the Native SDKs so as not to add in the potential for decency issues we didn't test with.

Upgrading to `3.22.1` may be the solution, but we need to confirm.

**Comment by Jmilham21** [comment]
I am closing this as it is resolved via upgrading the IMA dependency. 

As a heads up, in future versions we may revert back to specific version numbers for dependices to better maintain this library. Things like `'GoogleAds-IMA-iOS-SDK', '~> 3.22'` could cause upgrades we aren't ready to support (though a patch upgrade shouldn't break our code base).
