### ISSUE TITLE
[ASK] Are video thumbnails tracks supported?

### ISSUE THREAD

**Issue by fdobre** [jwplayer/jwplayer-react-native#57]
Are video tracks with thumbnails supported?

```
tracks: [{
                file: "https://cdn.jwplayer.com/strips/xzxKu91o-120.vtt",
                label: 'track1',
                default: true,
                kind: "thumbnails",
              }].
```

Web seems to support such feature when user moves the current position of timeslider.

<img width="311" alt="Screenshot 2024-07-09 at 20 11 24" src="https://github.com/jwplayer/jwplayer-react-native/assets/3833179/0400baca-b65d-4cde-8b5b-7b164b75df47">

**Comment by Jmilham21** [comment]
Hi @fdobre, yes you can use thumbnail tracks. See the below config to be used in our `Example` app. 

This should also work in legacy configs on both platforms. 

```js
  let jwConfig = {
    "title": "Single Inline Linear Preroll",
    "playlist": [
      {
        "file": "https://content.bitsontherun.com/videos/q1fx20VZ-52qL9xLP.mp4",
        "tracks": [
          {
            file: "https://cdn.jwplayer.com/strips/xzxKu91o-120.vtt",
            label: 'track1',
            default: true,
            kind: "thumbnails",
          }
        ]
      }
    ]
  }
```

**Comment by fdobre** [comment]
@Jmilham21 Tested, it works great!
