### ISSUE TITLE
[BUG] PiP not working on iOS

### ISSUE THREAD

**Issue by MantasMikal** [jwplayer/jwplayer-react-native#70]
### PiP not working on iOS

https://github.com/user-attachments/assets/ca6ac0f3-8717-42ad-926f-681543f9c15b

**To Reproduce**

Clone https://github.com/MantasMikal/jwplayer-react-native-ios-issues

***Steps to reproduce the issue:***

1. Go to 'PiP Example' screen on iOS
2. Minimise the app

**Device(s) affected**
 - Device: iPhone 15
 - OS: 17.2

**JWP Ticketing**

https://support.jwplayer.com/hc/requests/144762

**Comment by Jmilham21** [comment]
@MantasMikal, this should now be resolved in the `Master` branch. PiP isn't available on iPhone Simulators (generally), so you'll need to test on a physical device or a properly configured Simulator (I'm not sure if this is possible, but I'm not well-versed in simulators). 

If you need the same behavior in iOS as you demoed in Android, you may need to modify the Swift code slightly to put the player in PiP when the app is backgrounded (not the default behavior). 

Leaving this open for your approval.

**Comment by MantasMikal** [comment]
Thank you very much @Jmilham21 it works great 👍

FYI, PiP works fine on iPad sims if want to test with simulator :)
