### ISSUE TITLE
[FEAT] Please provide Flutter SDK for jwPlayer

### ISSUE THREAD

**Issue by nateshmbhat** [jwplayer/jwplayer-react-native#76]
JwPlayer doesn't have an official flutter sdk. These days all greenfield projects are choosing flutter for mobile app development. Not having JWPlayer SDK available on flutter would be a big let down. 

Is there a plan for providing support for this anytime soon ? Would be great if you provide some rough timeline

**Comment by Jmilham21** [comment]
Hi @nateshmbhat, We don't plan to create and support a Flutter plugin for our native SDKs. If this is a need, I'd suggest making your own [plugin](https://docs.flutter.dev/packages-and-plugins/developing-packages) around our SDK, similar to how this repository does for React Native. I'd recommend checking out this [repository](https://github.com/DavidPerezP124/jwplayer_plugin), which a former employee made as an introductory guide to Flutter. It could serve as a starting point if you want to create your own interface.

I have brought your request up with our product team, but it would be helpful if you also logged this with your account manager or our support team via our [requests](https://support.jwplayer.com/hc/en-us/requests/new) portal so we can associate the ask with your account. I can't promise we will end up supporting Flutter, but the more interested customers, the more likely we will.
