### ISSUE TITLE
[BUG] [Android] Previous video gets played on the Chromecast device 

### ISSUE THREAD

**Issue by fdobre** [jwplayer/jwplayer-react-native#82]
**Describe the bug**
 Previous video gets played on the Chromecast device 

**To Reproduce**
1. Play a video
2. Close player and open another video
3. Chromecast the video on a device
4. Observe that previous video is played on the casting device

**Expected behavior**
Current video should be played on the chrome casting device, not previous one

`"@jwplayer/jwplayer-react-native": "^1.0.1",`

This bug seems to be the same as the one mentioned here:

https://github.com/chaimPaneth/react-native-jw-media-player/issues/282

**Comment by Jmilham21** [comment]
Hey @fdobre, I have a PR up that should resolve this. Please take a look if you have a second. It will be patched in the next release to NPM after I can get an internal review.

**Comment by fdobre** [comment]
@Jmilham21 Sorry I am away from the project for about 10 days. I won't be able to check this until next week.

**Comment by fdobre** [comment]
@Jmilham21 Tested the PR with many videos. There is definitely a big improvement. 

I can confirm the issue already mentioned at the PR is present: if current video playing ends you have to close current casting and open a new one for the next video otherwise you will just see the casting icon on the target device screen.

The good news is patch allows to play current video, you can play another video immediately (unless you allow current one to reach the end) or by closing and reopening the casting connection.
