### ISSUE TITLE
[BUG] No such module GoogleCast

### ISSUE THREAD

**Issue by chriszs** [jwplayer/jwplayer-react-native#9]
**Describe the bug**
Without enabling Google Cast support, iOS compilation fails with "No such module GoogleCast" error, which points to [an import in RNJWPlayerView](https://github.com/jwplayer/jwplayer-react-native/blob/5b68985aea8392777bb257fab70e1cecd731d3a7/ios/RNJWPlayer/RNJWPlayerView.swift#L14). It looks this was [a known issue](https://github.com/chaimPaneth/react-native-jw-media-player/issues/345) in the original version of the library, which the author [may have addressed in late February](https://github.com/chaimPaneth/react-native-jw-media-player/commit/8d6c6754e420880092f66165c9e117af94d30ee4) (this code was subsequently modified to fix some issues it introduced). That fix doesn't appear to have made it to this fork.

**To Reproduce**
I installed it in a React Native application and tried to build for iOS without Google Cast support.

**Expected behavior**
It should build without the Google Cast import if Google Cast support isn't enabled.

**Screenshots / Visual evidence**
<img width="573" alt="Screenshot 2024-05-04 at 1 19 43 AM" src="https://github.com/jwplayer/jwplayer-react-native/assets/1103467/5745a25a-3f58-43db-af17-53687314a2bc">

**Desktop (please complete the following information):**
 - Result of `npx react-native info`
 
```
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M2
  Memory: 120.70 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.asdf/installs/nodejs/18.17.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.asdf/installs/nodejs/18.17.1/bin/yarn
  npm:
    version: 10.5.2
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/admin/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /Users/admin/.asdf/shims/javac
  Ruby:
    version: 2.6.10
    path: /Users/admin/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by Jmilham21** [comment]
This has been resolved per the associated PR. I will push this and a few other updates into a release to NPM this week. Thank you, @chriszs, for raising this, and @chaimPaneth, for the quick resolution.

**Comment by chriszs** [comment]
Thanks both of you!
