### ISSUE TITLE
[ASK] Is there a Roadmap for this react native library?

### ISSUE THREAD

**Issue by paulrinaldi** [jwplayer/jwplayer-react-native#95]
**What isn't clear?**
I'm wondering what the roadmap for fixes and features looks like for JW Player React Native.

**Comment by Jmilham21** [comment]
Hi @paulrinaldi, sorry for the late response. We don't have a roadmap for this library. This project is maintained reactively, so we keep it relatively up-to-date, but most of our work is from raised issues/feature requests / or general maintenance. 

We strive for parity between this library and our native SDKs, but we know things aren't perfectly 1:1 right now. If you see anything you want implemented from the [documentation](https://docs.jwplayer.com/players/docs/players-welcome), please reach out or create a PR, and we can work to get it added/merged 👍
